/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import HashMap from '@ohos.util.HashMap';
import { AxisBase, IAxisValueFormatter } from '@ohos/mpchart';

export class ChartAxisFormatter implements IAxisValueFormatter {
  xAxis: HashMap<number, string> = new HashMap();

  constructor(xAxis: HashMap<number, string>) {
    this.xAxis = xAxis;
  }

  public getFormattedValue(value: number, axis: AxisBase): string {
    return this.xAxis.get(value);
  }
}