/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Transaction constants for transaction feature.
 */
export class TransactionConstants {
  /**
   * Row space.
   */
  static readonly ROW_SPACE: number = 12;

  /**
   * Purchase rates.
   */
  static readonly RATE_VALUE: number = 0;

  /**
   * Rate confirmation date.
   */
  static readonly RATE_MOUTH: number = 8;

  /**
   * Rate confirmation date.
   */
  static readonly RATE_DAY: number = 18;
}