/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Fund constants for fund feature.
 */
export class FundConstants {
  /**
   * Row space.
   */
  static readonly ROW_SPACE: number = 8;

  /**
   * Column space.
   */
  static readonly COLUMN_SPACE: number = 6;

  /**
   * Column space.
   */
  static readonly TAB_COLUMN_SPACE: number = 4;

  /**
   * Row space.
   */
  static readonly BOTTOM_ROW_SPACE: number = 24;

  /**
   * Row space.
   */
  static readonly TAB_ROW_SPACE: number = 20;

  /**
   * Column space.
   */
  static readonly BOTTOM_COLUMN_SPACE: number = 24;

  /**
   * Row space.
   */
  static readonly COLLECT_COLUMN_SPACE: number = 4;

  /**
   * Get fund info start index.
   */
  static readonly FUND_COUNT_START: number = 0;

  /**
   * Get fund info under sm power outage.
   */
  static readonly FUND_COUNT_SM: number = 4;

  /**
   * Get fund info under md power outage.
   */
  static readonly FUND_COUNT_MD: number = 6;

  /**
   * Get fund info under lg power outage.
   */
  static readonly FUND_COUNT_LG: number = 12;

  /**
   * Get list lanes under sm power outage.
   */
  static readonly LIST_LANES_SM: number = 2;

  /**
   * Get list lanes under md power outage.
   */
  static readonly LIST_LANES_MD: number = 3;

  /**
   * Get list lanes under lg power outage.
   */
  static readonly LIST_LANES_LG: number = 5;

  /**
   * Get button count under sm power outage.
   */
  static readonly BUTTON_COUNT_SM: number = 5;

  /**
   * Get button count under md power outage.
   */
  static readonly BUTTON_COUNT_MD: number = 6;

  /**
   * Get column count under sm power outage.
   */
  static readonly COLUMN_COUNT_SM: number = 2;

  /**
   * Get column count under md power outage.
   */
  static readonly COLUMN_COUNT_MD: number = 3;

  /**
   * Gradient position.
   */
  static readonly GRADIENT_LEFT: number = 0;

  /**
   * Gradient position.
   */
  static readonly GRADIENT_CENTER: number = 0.91;

  /**
   * Gradient position.
   */
  static readonly GRADIENT_RIGHT: number = 1;

  /**
   * Calculate the position value.
   */
  static readonly CALCULATE_POSITION_LG: number = 216;

  /**
   * Calculate the position value.
   */
  static readonly CALCULATE_POSITION: number = 146;

  /**
   * Nav bar width.
   */
  static readonly NAV_BAR_WIDTH: string = '40%';
}