/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class HomeConstants {
  /**
   * Top tab topics.
   */
  static readonly TOP_TOPIC_LIST: string[] = ['精选', '视频', '社区', '新闻', '购物', '科技', '财经', '历史', '军事'];

  /**
   * Icon list.
   */
  static readonly ICON_LIST: string[] = ['全部', '周热榜', '免费', '经典', '专区', '儿童专区', '华为专区', '付费精品',
    '健身专区'];

  /**
   * Banner text 1.
   */
  static readonly BANNER_TEXT_1: string[] = ['HUAWEI ', 'Mate Book 系列', '新  品  发  布  会'];

  /**
   * Banner text 2.
   */
  static readonly BANNER_TEXT_2: string[] = ['HUAWEI ', '折叠旗舰及全场景', '新  品  发  布  会'];

  /**
   * Banner text 3.
   */
  static readonly BANNER_TEXT_3: string[] = ['HUAWEI P60 系列', '', '华为春季旗舰新品发布会'];

  /**
   * Banner text 4.
   */
  static readonly BANNER_TEXT_4: string[] = ['万     象     新     生', '', '华 为 旗 舰 新 品 发 布 会'];

  /**
   * Video grid rate list.
   */
  static readonly VIDEO_GRID_RATES: string[] = ['7.8', '8.0', '7.9', '8.4', '7.8', '8.0', '7.9', '8.4', '7.6', '8.0'];

  /**
   * Video grid name list.
   */
  static readonly VIDEO_GRID_NAMES: string[] = ['建筑人文史迹', '生命之谜语', '世界十大神奇建筑', '舞动者们', '动物大迁徙',
    '深海诱惑', '爱丽丝的秘密花园', '山河壮丽 下集', '童话王国', '我的世界'];

  /**
   * Video grid content list.
   */
  static readonly VIDEO_GRID_CONTENTS: string[] = ['欧洲建筑的历史责任在载对欧洲建筑风格的形成和...',
    '小小世界的生存智慧是非常复杂的，有社会环境...', '世界十大神奇建筑指的是建筑造型或地点十分独...',
    '世界十大神奇建筑指的是建筑造型或地点十分独...', '每年6月左右，坦桑尼亚大草原的青草逐渐消耗...',
    '深海险象环生，人类为何仍热衷潜水运动，海底...', '作家爱丽丝有一个不为人知的秘密花园，每当她...',
    '这是千百年前的痕迹是经过风吹日晒才逐渐形成...', '一觉醒来，湛蓝的天空，连风都是温...', '卢卡斯有一只神奇的猫咪，每当它静...'];

  /**
   * New video grid rate list.
   */
  static readonly NEW_VIDEO_RATES: string[] = ['', '', '7.9', '7.9', '7.9', '7.9', '7.9'];

  /**
   * New video name list.
   */
  static readonly NEW_VIDEO_NAMES: string[] = ['HUAWEI Mate30 新...', '华为全场景智慧生活...', '自然地貌一览', '探海神秘',
    '山河壮丽 中集', '父与子', '山河壮丽 上集'];

  /**
   * New video content list.
   */
  static readonly NEW_VIDEO_CONTENTS: string[] = ['全球新品发布...', '华为终端·华为智慧生活...', '亿万年前地貌的形成都通...',
    '海洋，是世界上最伟大的...', '亿万年前地貌的形成都通...', '在一个风雨交加的夜晚...', '亿万年前地貌的形成都通...'];

  /**
   * Main daily video rate.
   */
  static readonly MAIN_DAILY_VIDEO_RATE: string = '8.4';

  /**
   * Main daily video name.
   */
  static readonly MAIN_DAILY_VIDEO_NAME: string = '生命之源：探索生命之源';

  /**
   * Main daily video content.
   */
  static readonly MAIN_DAILY_VIDEO_CONTENT: string = '探索生命之源';

  /**
   * Main daily video more info.
   */
  static readonly MAIN_DAILY_VIDEO_MORE: string = '生命之源';

  /**
   * Daily video rate list.
   */
  static readonly DAILY_VIDEO_RATES: string[] = ['8.4', '8.4', '8.4', '8.4'];

  /**
   * Daily video name list.
   */
  static readonly DAILY_VIDEO_NAMES: string[] = ['孤独者', '日照金山', '女侦探黛西', '我和我的家乡'];

  /**
   * Daily video name list.
   */
  static readonly DAILY_VIDEO_CONTENTS: string[] = ['凯里是一个思想及灵魂...', '日照金山是梅里雪上独...',
    '黛西是这个街区最有名...', '我的家乡在很遥远的山...'];

  /**
   * Previous video name list one.
   */
  static readonly PREVIOUS_VIDEO_NAMES_ONE: string[] = ['海边往事', '华为折叠屏旗舰及全场景新品发布会',
    '2022华为全屋智能及全场景新品春季...'];

  /**
   * Previous video content list one.
   */
  static readonly PREVIOUS_VIDEO_CONTENTS_ONE: string[] = ['电影 · 剧情片 · 2008年上...', '华为终端 · 发布会 · 202...',
    '华为终端 · 华为资讯 · 20...'];

  /**
   * Previous video more info list one.
   */
  static readonly PREVIOUS_VIDEO_MORE_ONE: string[] = ['75.2万次播放', '9.8万次播放', '10.1万次播放'];

  /**
   * Previous video name list two.
   */
  static readonly PREVIOUS_VIDEO_NAMES_TWO: string[] = ['华为全场景智慧生...', '神秘人X', '华为全场景智慧...',
    '星球故事', '华为全场景智慧生...', '折叠万象'];

  /**
   * Previous video content list two.
   */
  static readonly PREVIOUS_VIDEO_CONTENTS_TWO: string[] = ['华为终端·华为资讯·...', '至今没有公开自己是...',
    '华为终端·华为资讯·...', '在遥远的宇宙中有无...', '华为终端·华为资讯·...', '华为冬季旗舰新品发...'];

  /**
   * XComponent type.
   */
  static readonly X_COMPONENT_TYPE: string = 'surface';

  /**
   * Banner text letter space list.
   */
  static readonly BANNER_TEXT_LETTER_SPACES: string[] = ['2vp', '3vp', '1vp'];

  /**
   * Swiper item space.
   */
  static readonly SWIPER_ITEM_SPACE: string = '12vp';

  /**
   * Banner row space.
   */
  static readonly BANNER_ROW_SPACE: string = '12vp';

  /**
   * Home sub title list.
   */
  static readonly HOME_SUB_TITLES: string[] = ['新片发布', '每日佳片', '往期回顾'];

  /**
   * New video rows template.
   */
  static readonly NEW_VIDEO_ROWS_TEMPLATE: string = '1fr';

  /**
   * Search top tab bar list space list.
   */
  static readonly SEARCH_TAB_LIST_SPACES: string[] = ['16vp', '24vp', '36vp'];

  /**
   * Main daily video button text.
   */
  static readonly HOME_BUTTON_TEXT: string[] = ['关注', '继续播放', '播放', '缓存'];

  /**
   * Previous two list translate position.
   */
  static readonly PREVIOUS_TWO_TRANSLATE_MD: string = '-42vp';

  /**
   * Search placeholder.
   */
  static readonly SEARCH_PLACEHOLDER: string = '搜索...';

  /**
   * Video dialog option list.
   */
  static readonly VIDEO_DIALOG_OPTIONS: string[] = ['追剧', '收藏', '点赞'];

  /**
   * Side bar icon list height.
   */
  static readonly SIDE_ICON_LIST_HEIGHT: string = '25%';

  /**
   * Square brackets.
   */
  static readonly SQUARE_BRACKETS: string[] = ['[', ']'];

  /**
   * Height unit.
   */
  static readonly HEIGHT_UNIT: string = 'vp';

  /**
   * Two.
   */
  static readonly TWO: number = 2;

  /**
   * Five.
   */
  static readonly FIVE: number = 5;

  /**
   * Six.
   */
  static readonly SIX: number = 6;

  /**
   * Seven.
   */
  static readonly SEVEN: number = 7;

  /**
   * Eight.
   */
  static readonly EIGHT: number = 8;

  /**
   * Video dialog height list.
   */
  static readonly VIDEO_DIALOG_HEIGHTS: number[] = [161, 268, 347];

  /**
   * Video dialog aspect ratio.
   */
  static readonly VIDEO_DIALOG_ASPECT_RATIO: number = 1.74;

  /**
   * New banner aspect ratio.
   */
  static readonly NEW_BANNER_ASPECT_RATIO: number = 1.5;

  /**
   * Home header background change height.
   */
  static readonly BACKGROUND_CHANGE_HEIGHT: number[] = [27, 34, 56];

  /**
   * Video grid item space.
   */
  static readonly VIDEO_GRID_ITEM_SPACE: number = 12;

  /**
   * Video grid margin.
   */
  static readonly VIDEO_GRID_MARGIN: number[] = [32, 48, 64];

  /**
   * Number of displayed icons.
   */
  static readonly DISPLAYED_ICON_NUMBER: number[] = [9, 13, 17];

  /**
   * Lg sidebar width.
   */
  static readonly LG_SIDEBAR_WIDTH: number = 96;

  /**
   * Video grid description height.
   */
  static readonly VIDEO_GRID_DESCRIPTION_HEIGHT: number = 114;

  /**
   * New video aspect ratio.
   */
  static readonly NEW_VIDEO_ASPECT_RATIO: number = 0.72;

  /**
   * New video description height.
   */
  static readonly NEW_VIDEO_DESCRIPTION_HEIGHT: number = 45;

  /**
   * Daily video description height.
   */
  static readonly DAILY_VIDEO_DESCRIPTION_HEIGHT: number[] = [103, 62];

  /**
   * Previous two ratio list.
   */
  static readonly PREVIOUS_TWO_RATIOS: number[] = [0.76, 0.89, 0.86, 0.74, 0.8, 0.9, 0.83];

  /**
   * Banner aspect ratio list.
   */
  static readonly BANNER_RATIOS: number[] = [1.5, 1.83, 2.33];

  /**
   * Home header height for sm.
   */
  static readonly HOME_HEADER_HEIGHT_SM: number = 112;

  /**
   * Window undefined top.
   */
  static readonly WINDOW_UNDEFINED_TOP: number = 39;

  /**
   * Window undefined left.
   */
  static readonly WINDOW_UNDEFINED_LEFT: number = 5;

  /**
   * Eleven.
   */
  static readonly ELEVEN: number = 11;

  /**
   * Banner text 1 left position for md.
   */
  static readonly BANNER_TEXT_1_LEFT_MD: string = '8%';

  /**
   * Banner text 2 left position for md.
   */
  static readonly BANNER_TEXT_2_LEFT_MD: string = '8%';

  /**
   * Banner text 2 left position for lg.
   */
  static readonly BANNER_TEXT_2_LEFT_LG: string = '5%';

  /**
   * Banner text 1 top position for sm.
   */
  static readonly BANNER_TEXT_1_TOP_SM: string[] = ['15%', '2vp'];

  /**
   * Banner text 1 top position for md.
   */
  static readonly BANNER_TEXT_1_TOP_MD: string[] = ['8%', '4vp'];

  /**
   * Banner text 1 top position for lg.
   */
  static readonly BANNER_TEXT_1_TOP_LG: string[] = ['5%', '2vp'];

  /**
   * Banner text 2 top position for sm.
   */
  static readonly BANNER_TEXT_2_TOP_SM: string[] = ['15%', '2vp'];

  /**
   * Banner text 2 top position for md.
   */
  static readonly BANNER_TEXT_2_TOP_MD: string[] = ['10%', '4vp'];

  /**
   * Banner text 2 top position for lg.
   */
  static readonly BANNER_TEXT_2_TOP_LG: string[] = ['10%', '8vp'];

  /**
   * Video detail url.
   */
  static readonly VIDEO_DETAIL_URL: string = '@bundle:com.huawei.videoapplication/videoDetail/ets/pages/Index';

  /**
   * Direction list.
   */
  static readonly DIRECTION_LIST: string[] = ['BottomTabs', 'TopTabs', 'Banner', 'IconList', 'RecommendedVideo',
    'NewRelease', 'DailyVideoOne', 'DailyVideoTwo', 'PreviousVideo'];

  /**
   * Percent 105.
   */
  static readonly PERCENT_HUNDRED_AND_FIVE: string = '105%';

  /**
   * Animation duration.
   */
  static readonly ANIMATION_DURATION: number = 500;
}