/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * Linear gradient angle.
   */
  static readonly LINEAR_GRADIENT_ANGLE: number = 180;

  /**
   * Linear gradient from.
   */
  static readonly LINEAR_GRADIENT_FROM: number = 0.01;

  /**
   * Linear gradient to.
   */
  static readonly LINEAR_GRADIENT_TO: number = 0.92;

  /**
   * Linear gradient from color.
   */
  static readonly LINEAR_GRADIENT_FROM_COLOR: string = '#80307AF8';

  /**
   * Linear gradient to color.
   */
  static readonly LINEAR_GRADIENT_TO_COLOR: string = '#000A59F7';

  /**
   * Subtitle opacity.
   */
  static readonly SUBTITLE_OPACITY: number = 0.6;

  /**
   * Swiper item space.
   */
  static readonly SWIPER_ITEM_SPACE: string = '20vp';

  /**
   * Title content space.
   */
  static readonly TITLE_CONTENT_SPACE: string = '4vp';

  /**
   * Top count.
   */
  static readonly TOP_COUNT: number = 3;

  /**
   * Window padding half sm.
   */
  static readonly WINDOW_PADDING_HALF_SM = '8vp';
}