/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * Comment bar input width.
   */
  static readonly COMMENT_BAR_INPUT_WIDTH: string = '40%';

  /**
   * Comment bar input margin left.
   */
  static readonly COMMENT_BAR_INPUT_ML: string = '4.4%';

  /**
   * Text area max lines.
   */
  static readonly TEXT_AREA_MAX_LINES: number = 8;

  /**
   * Text area max length.
   */
  static readonly TEXT_AREA_MAX_LENGTH: number = 500;

  /**
   * Time position space.
   */
  static readonly TIME_POSITION_SPACE: string = '8vp';

  /**
   * Review count space.
   */
  static readonly REVIEW_COUNT_SPACE: string = '2vp';

  /**
   * Sub content max lines.
   */
  static readonly SUB_CONTENT_MAX_LINES: number = 2;

  /**
   * List item space.
   */
  static readonly LIST_ITEM_SPACE: string = '8vp';

  /**
   * Max grid column.
   */
  static readonly MAX_GRID_COLUMN: number = 3;

  /**
   * Grid columns template.
   */
  static readonly GRID_COLUMNS_TEMPLATE: string = '1fr 1fr 1fr';

  /**
   * Pinch gesture fingers.
   */
  static readonly PINCH_GESTURE_FINGERS: number = 2;

  /**
   * Suffix fp.
   */
  static readonly SUFFIX_FP: string = 'fp';

  /**
   * Suffix vp.
   */
  static readonly SUFFIX_VP: string = 'vp';

  /**
   * Max scale.
   */
  static readonly MAX_SCALE: number = 1.45;

  /**
   * Min scale.
   */
  static readonly MIN_SCALE: number = 0.75;

  /**
   * Content font size.
   */
  static readonly CONTENT_FONT_SIZE: number = 16;

  /**
   * Content font height.
   */
  static readonly CONTENT_FONT_HEIGHT: number = 25.6;

  /**
   * Picture margin top.
   */
  static readonly PICTURE_MARGIN_TOP: number = 8;
}