/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * Rank item margin left sm.
   */
  static readonly RANK_ITEM_ML_SM: string = '2.2%';

  /**
   * Rank item margin left md.
   */
  static readonly RANK_ITEM_ML_MD: string = '1.2%';

  /**
   * Rank item margin left lg.
   */
  static readonly RANK_ITEM_ML_LG: string = '1.2%';

  /**
   * Rank title margin left.
   */
  static readonly RANK_TITLE_MARGIN_LEFT: string = '2.2%';

  /**
   * Search bar width md.
   */
  static readonly SEARCH_BAR_WIDTH_MD: string = '27.2%';

  /**
   *Search bar width lg.
   */
  static readonly SEARCH_BAR_WIDTH_LG: string = '18.1%';

  /**
   * Animation duration.
   */
  static readonly TAB_ANIMATION_DURATION: number = 300;

  /**
   * Water flow columns template normal.
   */
  static readonly WATER_FLOW_COLUMNS_TEMPLATE_NORMAL: string = '1fr';

  /**
   * Water flow columns template lg.
   */
  static readonly WATER_FLOW_COLUMNS_TEMPLATE_LG: string = '1fr 1fr';

  /**
   * Hot column item space sm.
   */
  static readonly HOT_COLUMN_IS_SM:string = '0vp';

  /**
   * Hot column item space md.
   */
  static readonly HOT_COLUMN_IS_MD:string = '49vp';

  /**
   * Hot column item space lg.
   */
  static readonly HOT_COLUMN_IS_LG:string = '81vp';

  /**
   * Swiper display count one.
   */
  static readonly SWIPER_DISPLAY_COUNT_ONE: number = 1;

  /**
   * Swiper display count two.
   */
  static readonly SWIPER_DISPLAY_COUNT_TWO: number = 2;

  /**
   * Swiper display count three.
   */
  static readonly SWIPER_DISPLAY_COUNT_THREE: number = 3;

  /**
   * Hot column max count.
   */
  static readonly HOT_COLUMN_MAX_COUNT: number = 5;

  /**
   * Hot item column space.
   */
  static readonly HOT_ITEM_COLUMN_SPACE: string = '4vp';

  /**
   * Top count.
   */
  static readonly TOP_COUNT: number = 3;

  /**
   * Search bar opacity.
   */
  static readonly SEARCH_BAR_OPACITY: number = 0.9;

  /**
   * Card item shadow radius.
   */
  static readonly CARD_ITEM_SHADOW_RADIUS: number = 10;

  /**
   * Icon more opacity.
   */
  static readonly ICON_MORE_OPACITY: number = 0.4;

  /**
   * Window padding sm.
   */
  static readonly WINDOW_PADDING_SM: string = '16vp';

  /**
   * Window padding md.
   */
  static readonly WINDOW_PADDING_MD: string = '23vp';

  /**
   * Window padding lg.
   */
  static readonly WINDOW_PADDING_LG: string = '32vp';

  /**
   * Linear gradient angel.
   */
  static readonly LINEAR_GRADIENT_ANGEL: number = 180;

  /**
   * Linear gradient from color.
   */
  static readonly LINEAR_GRADIENT_FROM_COLOR: string = '#FFFFFF';

  /**
   * Linear gradient to color.
   */
  static readonly LINEAR_GRADIENT_TO_COLOR: string = '#F1F3F5';

  /**
   * Linear gradient to area.
   */
  static readonly LINEAR_GRADIENT_TO_AREA: number = 0.02;

  /**
   * Follow item picture max height.
   */
  static readonly FOLLOW_ITEM_PICTURE_MAX_HEIGHT: string = '60%';

  /**
   * Follow title space.
   */
  static readonly FOLLOW_TITLE_SPACE: string = '24vp';

  /**
   * Follow title content.
   */
  static readonly FOLLOW_TITLE_CONTENT: string = '的动态';
}