/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Home constants for home feature.
 */
export class HomeConstants {
  /**
   * Title row space.
   */
  static readonly TITLE_ROW_SPACE: number = 16;

  /**
   * Gps row space.
   */
  static readonly GPS_ROW_SPACE: number = 4;

  /**
   * List space.
   */
  static readonly LIST_SPACE: number = 12;

  /**
   * Main business row space.
   */
  static readonly MAIN_ROW_SPACE: number = 8;

  /**
   * Button row space.
   */
  static readonly BUTTON_ROW_SPACE: number = 4;

  /**
   * List sliding offset.
   */
  static readonly LIST_SLIDING_OFFSET: number = -800;

  /**
   * Get business data start index.
   */
  static readonly BUSINESS_DATA_COUNT_START: number = 0;

  /**
   * Get business data under sm power outage.
   */
  static readonly BUSINESS_DATA_COUNT_SM: number = 4;

  /**
   * Get business data under md power outage.
   */
  static readonly BUSINESS_DATA_COUNT_MD: number = 6;

  /**
   * Get business data under lg power outage.
   */
  static readonly BUSINESS_DATA_COUNT_LG: number = 8;

  /**
   * Get swiper display count under sm power outage.
   */
  static readonly SWIPER_DISPLAY_COUNT_SM: number = 1;

  /**
   * Get swiper display count under md power outage.
   */
  static readonly SWIPER_DISPLAY_COUNT_MD: number = 2;

  /**
   * Get swiper display count under lg power outage.
   */
  static readonly SWIPER_DISPLAY_COUNT_LG: number = 4;

  /**
   * Get list lanes count under sm power outage.
   */
  static readonly LIST_LANES_COUNT_SM: number = 1;

  /**
   * Get list lanes count under md power outage.
   */
  static readonly LIST_LANES_COUNT_MD: number = 2;

  /**
   * Get list lanes count under lg power outage.
   */
  static readonly LIST_LANES_COUNT_LG: number = 4;

  /**
   * Get swiper item space under sm power outage.
   */
  static readonly SWIPER_SPACE_SM: number = 13;

  /**
   * Get swiper item space under md power outage.
   */
  static readonly SWIPER_SPACE_MD: number = 13;

  /**
   * Get swiper item space under lg power outage.
   */
  static readonly SWIPER_SPACE_LG: number = 16;
}