/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * Full percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * Half percent.
   */
  static readonly HALF_PERCENT: string = '50%';

  /**
   * Font weight 500.
   */
  static readonly FONT_WEIGHT_500: number = 500;

  /**
   * Font weight 700.
   */
  static readonly FONT_WEIGHT_700: number = 700;

  /**
   * Picture detail path.
   */
  static readonly PICTURE_DETAIL_PATH :string =
    '@bundle:com.huawei.multicommunityapplication/picture/ets/pages/PictureDetail';

  /**
   * Detail page path.
   */
  static readonly DETAIL_PAGE_PATH: string = '@bundle:com.huawei.multicommunityapplication/detail/ets/pages/DetailPage';

  /**
   * Hot rank page path.
   */
  static readonly HOT_RANK_PAGE_PATH: string = '@bundle:com.huawei.multicommunityapplication/rank/ets/pages/HotRankPage';

  /**
   * Rank title List.
   */
  static readonly RANK_TITLE_LIST: string[] = ['今日热搜', '要闻热搜', '同城热搜', '娱乐热搜', '美食热搜'];

  /**
   * Device 2in1.
   */
  static readonly DEVICE_2IN1: string = '2in1';
}