/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const CardList: Array<Resource> = [
  $r('app.media.ic_card_A'),
  $r('app.media.ic_card_B'),
  $r('app.media.ic_card_C'),
  $r('app.media.ic_card_D'),
  $r('app.media.ic_card_E'),
  $r('app.media.ic_card_F'),
  $r('app.media.ic_card_G'),
  $r('app.media.ic_card_H'),
  $r('app.media.ic_card_J'),
  $r('app.media.ic_card_K'),
  $r('app.media.ic_card_L'),
  $r('app.media.ic_card_M')
];